from google.appengine.ext import ndb

#########################
# Verb Data Store Model #
#########################

class Verb(ndb.Model):

    # id is automatically generated by the Data Store

    infinitive = ndb.StringProperty(required=True)
    pastSimple = ndb.StringProperty(required=True)
    pastParticiple = ndb.StringProperty(required=True)

    difficultyLevel = ndb.IntegerProperty(required=True)

    examples = ndb.StringProperty(repeated=True)